package com.michote.entity;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by jtq603 on 10/16/16.
 */

@Embeddable
public class HouseAddress {

    // An autogenerated id (unique for each user in the db)
    @Id
    private long houseAddressId;

    @NotNull
    private String city;

    @NotNull
    private String State;

    @NotNull
    private String country;

    @NotNull
    private String  zip;

    @NotNull
    private String address1;

    private String address2;

    public long getHouseAddressId() {
        return houseAddressId;
    }

    public void setHouseAddressId(long houseAddressId) {
        this.houseAddressId = houseAddressId;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return State;
    }

    public void setState(String state) {
        State = state;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getAddress1() {
        return address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }
}
