package com.michote.entity;

import java.util.List;

import javax.persistence.*;

/**
 * Created by jtq603 on 10/16/16.
 */

@Entity
@Table(name = "house")
public class House {
	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long houseId;
	private String title;
	private String description;
	private Double rent;
	private String availabelDate;
	private String postingDate;
	private String city;
	private String dog;
	private String sex;
	private String laoundry;
	private String cat;
	private String furnished;
	private String smooking;
	private String wheelChairAccessible;
	private String State;
	private String country;
	private String zip;
	private String address1;
	private String address2;
	private String parking;
	
	@OneToMany
    @JoinColumn(name="houseId")
	List<HouseImage> images;
	
	public List<HouseImage> getImages() {
		return images;
	}

	public void setImages(List<HouseImage> images) {
		this.images = images;
	}

	public String getParking() {
		return parking;
	}

	public void setParking(String parking) {
		this.parking = parking;
	}

	public String getDog() {
		return dog;
	}

	public void setDog(String dog) {
		this.dog = dog;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getLaoundry() {
		return laoundry;
	}

	public void setLaoundry(String laoundry) {
		this.laoundry = laoundry;
	}

	public String getCat() {
		return cat;
	}

	public void setCat(String cat) {
		this.cat = cat;
	}

	public String getFurnished() {
		return furnished;
	}

	public void setFurnished(String furnished) {
		this.furnished = furnished;
	}

	public String getSmooking() {
		return smooking;
	}

	public void setSmooking(String smooking) {
		this.smooking = smooking;
	}

	public String getWheelChairAccessible() {
		return wheelChairAccessible;
	}

	public void setWheelChairAccessible(String wheelChairAccessible) {
		this.wheelChairAccessible = wheelChairAccessible;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return State;
	}

	public void setState(String state) {
		State = state;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getAddress1() {
		return address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public long getHouseId() {
		return houseId;
	}

	public void setHouseId(long houseId) {
		this.houseId = houseId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getRent() {
		return rent;
	}

	public void setRent(Double rent) {
		this.rent = rent;
	}

	public String getAvailabelDate() {
		return availabelDate;
	}

	public void setAvailabelDate(String availabelDate) {
		this.availabelDate = availabelDate;
	}

	public String getPostingDate() {
		return postingDate;
	}

	public void setPostingDate(String postingDate) {
		this.postingDate = postingDate;
	}
}
