package com.michote.entity;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by jtq603 on 10/16/16.
 */

@Entity
@Table(name = "house")
public class House {
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long houseId;

    @NotNull
    private  String title;

    @NotNull
    private  String description;

    @NotNull
    private  Double rent;

    @NotNull
    private String availabelDate;

    @NotNull
    private String postingDate;

    @Embedded
    private HouseAddress houseAddress;

    public long getHouseId() {
        return houseId;
    }

    public void setHouseId(long houseId) {
        this.houseId = houseId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getRent() {
        return rent;
    }

    public void setRent(Double rent) {
        this.rent = rent;
    }

    public String getAvailabelDate() {
        return availabelDate;
    }

    public void setAvailabelDate(String availabelDate) {
        this.availabelDate = availabelDate;
    }

    public String getPostingDate() {
        return postingDate;
    }

    public void setPostingDate(String postingDate) {
        this.postingDate = postingDate;
    }
}
